on:
  issues:
    types: [opened]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: add triage label
        uses: kerhub/saved-replies@dd3633c3608fcc768978988b012871d66f98f7d6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          addedLabels: 'triageee'